{
  getObjects(
    bucket_slug: "loki-webinar-production",
    read_key: "TMNjyVSNbfE75hA7q92OTZex74Ye5NuIn20DRWNroYgRGj4y9Y",
    input: {
    query: {
      type: "homes"
    }
  }) {
		          objects {
                id
			    title
                metadata
                slug
		          }
    	        }
}
        